<%@ Page Title="" Language="C#" MasterPageFile="~/MyMaster.Master" AutoEventWireup="true" CodeBehind="Profile.aspx.cs" Inherits="MyFirstProject.Profile" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-left: 7px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Profile Page</h1>
    <div class="row">
        <div class="col-lg-4 col-md-4">

        </div>
         <div class="col-lg-4 col-md-4">
             <h3 id="welcome" runat="server">Hi <asp:Label ID="lblName" runat="server"></asp:Label> Welcome, Here is Your Profile !!</h3>
             <h3 id="viewDetails" runat="server" visible="true">Wanna View or Edit Your details? 
                 <asp:LinkButton ID="lbDetails" runat="server" OnClick="lbDetails_Click">Click Here</asp:LinkButton> 
             </h3>
             <asp:DetailsView ID="DetailsViewProfile" runat="server" Height="241px" Width="577px" CellPadding="4" GridLines="None" CssClass="auto-style1" ForeColor="#333333" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnItemDeleting="DetailsViewProfile_ItemDeleting" OnModeChanging="DetailsViewProfile_ModeChanging">
                 <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                 <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                 <EditRowStyle BackColor="#999999" />
                 <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                 <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                 <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                 <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                 <RowStyle BackColor="#F7F6F3" ForeColor="#333333" Font-Bold="True" Font-Size="Large" />
             </asp:DetailsView>
         </div>
        <div class="col-lg-4 col-md-4">

        </div>

    </div>
</asp:Content>
